# Generated by Django 3.2.6 on 2021-08-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210828_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='display_pic',
            new_name='display_profile',
        ),
    ]
