# Generated by Django 3.2.6 on 2021-08-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_display_pic_userprofile_display_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='facebook_id',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='instagram_id',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='twitter_id',
            new_name='twitter',
        ),
    ]
