# Generated by Django 3.2.6 on 2021-08-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='thumb_alt',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
