# Generated by Django 3.2.6 on 2021-08-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag',
            new_name='tags',
        ),
    ]
