# Generated by Django 3.2.6 on 2021-08-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_tag_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
