# Generated by Django 3.2.6 on 2021-08-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_excerpt_in_article',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
