# Generated by Django 3.2.6 on 2021-09-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='tag', to='article.Tag'),
        ),
    ]
