# Generated by Django 3.2.6 on 2021-09-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_article_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-datetime']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='datetime',
        ),
    ]
