# Generated by Django 3.2.6 on 2021-09-04 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0013_auto_20210901_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_anonymous', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('additional_info', models.TextField(blank=True, max_length=500)),
                ('thumb', models.ImageField(blank=True, upload_to='')),
                ('thumb_alt', models.CharField(blank=True, default='', max_length=50)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('documents', models.FileField(blank=True, upload_to='documents/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
