# Generated by Django 3.2.6 on 2021-09-04 18:06

import article.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_articlesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesubmission',
            name='documents',
            field=models.FileField(upload_to='documents/', validators=[article.validators.validate_file_size]),
        ),
    ]
