# Generated by Django 3.2.9 on 2021-12-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_articlesubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='article/article_thumbs'),
        ),
        migrations.AlterField(
            model_name='articlesubmission',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='article/submissions/submission_thumbs'),
        ),
    ]
